name: Build and Publish

on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.API_TOKEN }}
        
    - name: Increment Version
      run: |
        # Read current version
        CURRENT_VERSION=$(cat VERSION)
        
        # Increment patch version
        IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
        PATCH_VERSION=$((${VERSION_PARTS[2]} + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
        
        # Update VERSION file
        echo $NEW_VERSION > VERSION
        
    - name: Build and Push
      run: |
        # Get the new version
        NEW_VERSION=$(cat VERSION)
        
        # Build and push the image
        docker build -t ghcr.io/sva-s1/syslog:$NEW_VERSION .
        docker push ghcr.io/sva-s1/syslog:$NEW_VERSION
        docker tag ghcr.io/sva-s1/syslog:$NEW_VERSION ghcr.io/sva-s1/syslog:latest
        docker push ghcr.io/sva-s1/syslog:latest
