name: Test Project
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
  push:
    branches: ['**']

env:                     # ↙︎ pull once, reuse everywhere
  IMAGE_NC:   ghcr.io/sva-s1/alpine-nc:latest
  IMAGE_SYS:  ghcr.io/sva-s1/syslog:latest
  PORT1_NUM:  ${{ vars.PORT1_NUMBER }}
  PORT1_PROTO:${{ vars.PORT1_PROTOCOL }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.API_TOKEN }}

      - name: Pull test images
        run: |
          docker pull $IMAGE_NC
          docker pull $IMAGE_SYS

      - name: Spin up syslog-ng
        run: |
          echo "S1_HEC_WRITE_TOKEN=${{ secrets.S1_HEC_WRITE_TOKEN }}"   > .env
          echo "S1_HEC_URL=${{ vars.S1_HEC_URL }}"                     >> .env
          echo "PORT1_NUMBER=$PORT1_NUM"                               >> .env
          echo "PORT1_PROTOCOL=$PORT1_PROTO"                           >> .env
          docker compose up -d

      - name: Blast sample logs
        run: |
          send () {
            sed -e "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$(date '+%Y-%m-%d %H:%M:%S')\"/" "$1" |
            docker run -i --rm \
              --add-host host.docker.internal:host-gateway \
              $IMAGE_NC /bin/ash -c "nc -u -w2 host.docker.internal $PORT1_NUM"
          }
          send samples/linux-sample.log
          send samples/fortigate-sample.log
          send samples/zscaler-sample.log

      - name: Teardown
        if: always()
        run: docker compose down -v
        rm -f .env        # wipe the temp file
