---                       # yamllint: document-start

name: test-project

on:
  workflow_dispatch: {}

  # every 15 min, Monday-Friday, 09-17 US-Eastern
  schedule:
    # EDT (UTC-4)  — Mar-Oct
    - cron: "*/15 13-21 * 3-10 1-5"
    # EST (UTC-5)  — Nov-Feb
    - cron: "*/15 14-22 * 11,12,1,2 1-5"

  push:
    branches:
      - "**"

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.API_TOKEN }}

      - name: Write .env for compose
        run: |
          echo "S1_HEC_WRITE_TOKEN=${{ secrets.S1_HEC_WRITE_TOKEN }}"  > .env
          echo "S1_HEC_URL=${{ vars.S1_HEC_URL }}"                    >> .env
          echo "PORT1_NUMBER=${{ vars.PORT1_NUMBER || '5514' }}"      >> .env
          echo "PORT1_PROTOCOL=${{ vars.PORT1_PROTOCOL || 'udp' }}"   >> .env

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Test Linux logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail
          # Use the portable command that works on all systems
          sed -E "s/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?Z/$(date -u +'%Y-%m-%dT%H:%M:%SZ')/" \
            samples/linux-sample.log |
            tee /dev/stderr |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Test FortiGate logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail

          # ── capture "now" once ─────────────────────────────────────────────
          NOW_EPOCH_NS="$(date +%s%N)"           # 19-digit nanoseconds
          NOW_EPOCH_S="${NOW_EPOCH_NS::10}"      # seconds

          CURRENT_DATE="$(date -u -d "@${NOW_EPOCH_S}" '+%Y-%m-%d')"
          CURRENT_TIME="$(date -u -d "@${NOW_EPOCH_S}" '+%H:%M:%S')"
          EVENTTIME="${NOW_EPOCH_NS}"

          sed -e "s/date=[0-9-]*/date=${CURRENT_DATE}/" \
              -e "s/time=[0-9:]\{8\}/time=${CURRENT_TIME}/" \
              -e "s/eventtime=[0-9]\{19\}/eventtime=${EVENTTIME}/" \
              samples/fortigate-sample.log |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Test Zscaler logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail
          CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$CURRENT_DATETIME\"/" \
            samples/zscaler-sample.log |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Cleanup
        if: always()
        run: |
          docker compose down
          rm -f .env
