---                       # document-start (keeps yamllint quiet)

# yamllint disable rule:truthy
name: test-project

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - "**"
# yamllint enable rule:truthy

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.API_TOKEN }}

      - name: Write .env for compose
        run: |
          echo "S1_HEC_WRITE_TOKEN=${{ secrets.S1_HEC_WRITE_TOKEN }}"  > .env
          echo "S1_HEC_URL=${{ vars.S1_HEC_URL }}"                    >> .env
          echo "PORT1_NUMBER=${{ vars.PORT1_NUMBER || '5514' }}"      >> .env
          echo "PORT1_PROTOCOL=${{ vars.PORT1_PROTOCOL || 'udp' }}"   >> .env

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Test Linux logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail
          CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$CURRENT_DATETIME\"/" \
            samples/linux-sample.log |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Test FortiGate logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail
          CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$CURRENT_DATETIME\"/" \
            samples/fortigate-sample.log |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Test Zscaler logs
        env:
          PORT1_NUMBER: ${{ vars.PORT1_NUMBER || '5514' }}
        run: |
          set -euo pipefail
          CURRENT_DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
          sed "s/\"datetime\":\"[^\"]*\"/\"datetime\":\"$CURRENT_DATETIME\"/" \
            samples/zscaler-sample.log |
            docker run -i --rm --network host \
              ghcr.io/sva-s1/alpine-nc:latest \
              /bin/ash -c "nc -u -w 2 127.0.0.1 ${PORT1_NUMBER}"

      - name: Cleanup
        if: always()
        run: |
          docker compose down
          rm -f .env.example
